# Generated by Django 5.1.3 on 2024-12-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sellers',
        ),
        migrations.AddField(
            model_name='product',
            name='sellers',
            field=models.ManyToManyField(related_name='products', to='shop.seller'),
        ),
    ]
