# Generated by Django 5.1.3 on 2024-12-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_seller_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='images',
            new_name='image',
        ),
    ]
